// ============================================================
// DOMAIN RULES — 2-Layer Memory Engine
// ============================================================
// Organizes Kuma memory into 2 layers (the actions that are still
// exposed to agents — `domain_rules` was pruned with the gimmick pass):
//   Layer 2 — Architecture & Sequence Flow Map: .kuma/ARCHITECTURE_FLOW.md
//   Layer 3 — Known Code Gotchas: .kuma/KNOWN_GOTCHAS.md
//
// Agents can query/update these files via kuma_memory actions.
// The files are auto-initialized with templates on first access.
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { getProjectRoot } from "../utils/pathValidator.js";
import { sessionMemory } from "./sessionMemory.js";

export type MemoryLayer = "arch_flow" | "gotcha";

const LAYER_FILES: Record<MemoryLayer, { filename: string; label: string }> = {
  arch_flow: { filename: "ARCHITECTURE_FLOW.md", label: "Architecture & Sequence Flow" },
  gotcha: { filename: "KNOWN_GOTCHAS.md", label: "Known Code Gotchas" },
};

// ============================================================
// LAYER 2: Architecture & Sequence Flow Map
// ============================================================

const ARCH_FLOW_TEMPLATE = `# Architecture & Sequence Flow Map

Auto-generated by Kuma Memory Engine.
Document execution call chains and architectural dependencies.

## System Overview
<!-- High-level description of the system architecture -->

## Entry Points
<!-- Main entry points for the application -->
- 

## Execution Chains
<!-- Route -> Middleware -> Controller -> Service -> DB -->
\`\`\`
Request Flow:
  1. [Entry] -> [Middleware] -> [Handler] -> [Service] -> [DB]
\`\`\`

## Module Dependency Map
<!-- How modules depend on each other -->
- Module A depends on: Module B, Module C
- Module B depends on: Module D

## Data Flow
<!-- How data flows through the system -->
1. Input: 
2. Process: 
3. Storage: 
4. Output: 

## External Integrations
<!-- External services, APIs, databases -->
- 
`;

// ============================================================
// LAYER 3: Known Code Gotchas
// ============================================================

const GOTCHAS_TEMPLATE = `# Known Code Gotchas

Auto-generated by Kuma Memory Engine.
Catalog of fragile legacy contracts, edge cases, and unexpected framework quirks.

## How to Add a Gotcha

\`\`\`
kuma_memory({
  action: 'gotcha',
  scope: 'auth_middleware',
  content: 'The auth middleware expects req.user after JWT decode. Missing middleware causes silent 500.',
  filePath: 'src/middleware/auth.ts'
})
\`\`\`

## Active Gotchas

<!-- Format:
### [File Path] — [Short Description]
- **Issue**: [What happens]
- **Fix**: [How to handle it correctly]
- **Severity**: [low | medium | high | critical]
- **Added**: [Date]
-->

`;

// ============================================================
// PATH HELPERS
// ============================================================

function layerFilePath(layer: MemoryLayer): string {
  return path.join(getProjectRoot(), ".kuma", LAYER_FILES[layer].filename);
}

function ensureLayerFile(layer: MemoryLayer): string {
  const fp = layerFilePath(layer);
  if (!fs.existsSync(fp)) {
    const template = layer === "arch_flow" ? ARCH_FLOW_TEMPLATE : GOTCHAS_TEMPLATE;
    const dir = path.dirname(fp);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(fp, template, "utf-8");
    console.error(`[DomainRules] Auto-created ${LAYER_FILES[layer].filename}`);
  }
  return fp;
}

// ============================================================
// PUBLIC API
// ============================================================

/**
 * Read the content of a memory layer file.
 */
export function readLayer(layer: MemoryLayer): string {
  try {
    const fp = ensureLayerFile(layer);
    return fs.readFileSync(fp, "utf-8");
  } catch (err) {
    return `Error reading ${layer}: ${err}`;
  }
}

/**
 * Write content to a memory layer file.
 */
export function writeLayer(layer: MemoryLayer, content: string): string {
  try {
    const fp = ensureLayerFile(layer);
    fs.writeFileSync(fp, content, "utf-8");
    const label = LAYER_FILES[layer].label;
    sessionMemory.recordToolCall("kuma_memory", { action: `write_${layer}` });
    return `✅ **${label}** updated successfully.`;
  } catch (err) {
    return `❌ Failed to update ${layer}: ${err}`;
  }
}

/**
 * Append content to a layer file (e.g., add a new gotcha).
 */
export function appendToLayer(layer: MemoryLayer, entry: string): string {
  try {
    const fp = ensureLayerFile(layer);
    const existing = fs.readFileSync(fp, "utf-8");
    const newContent = existing.trimEnd() + "\n\n" + entry.trim() + "\n";
    fs.writeFileSync(fp, newContent, "utf-8");
    return `✅ Entry added to **${LAYER_FILES[layer].label}**.`;
  } catch (err) {
    return `❌ Failed to append: ${err}`;
  }
}

/**
 * Get the active gotchas list with file-path indexing for safety checks.
 */
export function getActiveGotchas(): Array<{
  filePath: string;
  description: string;
  severity: string;
  content: string;
}> {
  const results: Array<{ filePath: string; description: string; severity: string; content: string }> = [];
  try {
    const fp = ensureLayerFile("gotcha");
    const content = fs.readFileSync(fp, "utf-8");
    const lines = content.split("\n");
    let currentSection = "";
    let currentFilePath = "";
    let currentDesc = "";
    let currentSeverity = "";

    for (const line of lines) {
      const fileMatch = line.match(/^###\s+(.+?)\s*[—–-]+\s*(.+)/);
      if (fileMatch) {
        if (currentFilePath) {
          results.push({ filePath: currentFilePath, description: currentDesc, severity: currentSeverity, content: currentSection });
        }
        currentFilePath = fileMatch[1].trim();
        currentDesc = fileMatch[2].trim();
        currentSeverity = "medium";
        currentSection = line + "\n";
        continue;
      }
      const sevMatch = line.match(/- \*\*Severity\*\*:\s*(\w+)/);
      if (sevMatch) currentSeverity = sevMatch[1].toLowerCase();
      currentSection += line + "\n";
    }
    if (currentFilePath) {
      results.push({ filePath: currentFilePath, description: currentDesc, severity: currentSeverity, content: currentSection });
    }
  } catch { /* file doesn't exist yet */ }
  return results;
}

/**
 * Check if a given file path has any known gotchas.
 * Returns formatted warnings for use in safety pre-checks.
 */
export function checkFileGotchas(filePath: string): string[] {
  const gotchas = getActiveGotchas();
  const warnings: string[] = [];
  for (const g of gotchas) {
    if (filePath.includes(g.filePath) || g.filePath.includes(filePath)) {
      const icon = g.severity === "critical" ? "🔴"
        : g.severity === "high" ? "🟠"
          : g.severity === "medium" ? "🟡" : "🟢";
      warnings.push(`${icon} **Gotcha**: ${g.description} (${g.severity})`);
    }
  }
  return warnings;
}

