// ============================================================
// PACKAGE BRIEFS — Pre-computed architecture context (zero LLM)
// ============================================================
// "Shift left": derive per-package briefs from the graph + FS once,
// serve them as static markdown. Agents read instead of grep-reading.
// Regenerated on map refresh / post-commit; consumers check mtime TTL.
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { getProjectRoot } from "../utils/pathValidator.js";
import { getWorkspaceInfo } from "./workspaceIntelligence.js";
import { MAP_TTL_MS, isStale, formatAge } from "./cacheFreshness.js";

export const BRIEFS_DIR = ".kuma/briefs";

function briefsDir(root?: string): string {
  return path.join(root || getProjectRoot(), BRIEFS_DIR);
}

function slug(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 60) || "root";
}

/**
 * Build one package brief from graph data (no LLM, bounded queries).
 * Sections: entry points, top dependents (hubs), gotchas, tests.
 */
export async function buildPackageBrief(pkgName: string, pkgPath: string, _root: string): Promise<string> {
  const lines = [`# 📦 ${pkgName}`, "", `_Auto-generated by Kuma — do not edit. Regenerate via map refresh._`, ""];
  if (pkgPath && pkgPath !== ".") lines.push(`path: \`${pkgPath}\``, "");

  try {
    const { getDb } = await import("./kumaDb.js");
    const db = await getDb();

    // Entry points: files in this package with most incoming edges
    const like = pkgPath && pkgPath !== "." ? `%${pkgPath}%` : `%`;
    const stmt = db.prepare(`
      SELECT n.file_path as fp, COUNT(*) as cnt FROM edges e
      JOIN nodes n ON n.id = e.target_id
      WHERE n.file_path LIKE ? AND n.file_path NOT LIKE '%test%'
      GROUP BY n.file_path ORDER BY cnt DESC LIMIT 8
    `);
    stmt.bind([like]);
    const hubs: string[] = [];
    while (stmt.step()) {
      const r = stmt.getAsObject() as { fp: string; cnt: number };
      if (r.fp) hubs.push(`- \`${r.fp}\` (${r.cnt} refs)`);
    }
    stmt.free();
    lines.push(`## 🎯 Key files`, ...(hubs.length > 0 ? hubs : ["- (no graph data yet — run a scan)"]), "");

    // Gotchas in this package
    try {
      const g = db.prepare(
        `SELECT file_path, description, severity FROM known_gotchas WHERE status IN ('active','verified') AND (quarantined IS NULL OR quarantined = 0) AND file_path LIKE ? ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END LIMIT 5`
      );
      g.bind([like]);
      const rows: string[] = [];
      while (g.step()) {
        const r = g.getAsObject() as { file_path: string; description: string; severity: string };
        rows.push(`- [${r.severity}] \`${r.file_path}\` — ${String(r.description).substring(0, 100)}`);
      }
      g.free();
      lines.push(`## ⚠️ Gotchas`, ...(rows.length > 0 ? rows : ["- none"]), "");
    } catch {}

    // Tests in this package
    try {
      const t = db.prepare(
        `SELECT DISTINCT file_path FROM nodes WHERE type = 'test' AND file_path LIKE ? LIMIT 10`
      );
      t.bind([like]);
      const tests: string[] = [];
      while (t.step()) {
        const r = t.getAsObject() as { file_path: string };
        if (r.file_path) tests.push(`- \`${r.file_path}\``);
      }
      t.free();
      lines.push(`## 🧪 Tests`, ...(tests.length > 0 ? tests : ["- (run a scan to map tests)"]), "");
    } catch {}
  } catch {
    lines.push("_(graph unavailable — brief will fill in after a scan)_", "");
  }

  return lines.join("\n");
}

/** Regenerate all briefs (bounded: one file per package). Returns count. */
export async function refreshPackageBriefs(): Promise<{ count: number; dir: string }> {
  const root = getProjectRoot();
  const dir = briefsDir(root);
  try {
    const ws = await getWorkspaceInfo(root);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    let count = 0;
    const pkgs = ws.isWorkspace ? ws.packages : [{ name: "root", path: ".", isRoot: true } as never];
    for (const p of pkgs.slice(0, 20)) {
      const pkg = p as { name: string; path: string };
      const content = await buildPackageBrief(pkg.name, pkg.path, root);
      fs.writeFileSync(path.join(dir, `${slug(pkg.name)}.md`), content, "utf-8");
      count++;
    }
    return { count, dir };
  } catch {
    return { count: 0, dir };
  }
}

/** Brief freshness (mtime TTL). Null when missing. */
export function briefFreshness(pkgName: string): { exists: boolean; fresh: boolean; age: string } {
  try {
    const fp = path.join(briefsDir(), `${slug(pkgName)}.md`);
    if (!fs.existsSync(fp)) return { exists: false, fresh: false, age: "missing" };
    const ageMs = Date.now() - fs.statSync(fp).mtimeMs;
    return { exists: true, fresh: !isStale(Date.now() - ageMs, MAP_TTL_MS), age: formatAge(Date.now() - ageMs) };
  } catch {
    return { exists: false, fresh: false, age: "missing" };
  }
}

/** Read a brief (for session-start / map output). Null when missing. */
export function readBrief(pkgName: string, maxChars = 1200): string | null {
  try {
    const fp = path.join(briefsDir(), `${slug(pkgName)}.md`);
    if (!fs.existsSync(fp)) return null;
    const content = fs.readFileSync(fp, "utf-8");
    return content.length > maxChars ? content.slice(0, maxChars) + "\n…(truncated)" : content;
  } catch {
    return null;
  }
}
